export type SeedWord = {
  language: "en" | "ja";
  term: string;
  reading?: string;
  meaning: string;
  partOfSpeech: string;
  tags: string[];
  phase: "learned" | "current";
  example?: string;
  translation?: string;
  accent?: number;
  pitch?: string;
  accentVerified?: boolean;
};

const en = (
  term: string,
  meaning: string,
  partOfSpeech: string,
  group: string,
  phase: SeedWord["phase"] = "learned",
): SeedWord => ({ language: "en", term, meaning, partOfSpeech, tags: ["TOEIC", group, phase === "current" ? "当前学习" : "已学习"], phase });

const ja = (
  term: string,
  reading: string,
  meaning: string,
  partOfSpeech: string,
  group: string,
  phase: SeedWord["phase"] = "learned",
): SeedWord => ({ language: "ja", term, reading, meaning, partOfSpeech, tags: ["日语初级", group, phase === "current" ? "当前学习" : "已学习"], phase, accentVerified: false });

export const STUDY_VOCABULARY: SeedWord[] = [
  en("abandon", "放弃；遗弃", "v.", "Week 1 Day 1"),
  en("abduct", "绑架；诱拐", "v.", "Week 1 Day 1"),
  en("absorb", "吸收；理解", "v.", "Week 1 Day 1"),
  en("abuse", "滥用；虐待", "v./n.", "Week 1 Day 1"),
  en("accelerate", "加速；促进", "v.", "Week 1 Day 2"),
  { ...en("accessible", "可进入的；易获得的", "adj.", "Week 1 Day 2"), reading: "/əkˈsesəbəl/", example: "The station is easily accessible by bus.", translation: "乘公交可以方便地到达车站。" },
  en("accomplice", "共犯；帮凶", "n.", "Week 1 Day 2"),
  en("account", "账户；说明；占比", "n./v.", "Week 1 Day 2"),
  { ...en("accountant", "会计；会计师", "n.", "Week 1 Day 2"), reading: "/əˈkaʊntənt/" },
  { ...en("accumulate", "积累；积聚", "v.", "Week 1 Day 2"), reading: "/əˈkjuːmjəleɪt/", example: "Employees accumulate paid leave each month.", translation: "员工每月累积带薪休假。" },
  en("accurate", "准确的；精确的", "adj.", "Week 1 Day 2"),
  en("activism", "行动主义；社会运动", "n.", "Week 1 Day 2"),
  { ...en("adjacent", "邻近的；毗连的", "adj.", "Week 1 Day 2"), reading: "/əˈdʒeɪsənt/", example: "The meeting room is adjacent to the lobby.", translation: "会议室紧邻大厅。" },
  en("adversity", "逆境；困境", "n.", "Week 1 Day 3"),
  en("affidavit", "宣誓书；书面证词", "n.", "Week 1 Day 3"),
  en("aerospace", "航空航天的；航空航天业", "adj./n.", "Week 1 Day 3"),
  en("affordable", "负担得起的", "adj.", "Week 1 Day 3"),
  en("affluent", "富裕的；富足的", "adj.", "Week 1 Day 3"),
  en("aftershock", "余震", "n.", "Week 1 Day 3"),
  en("agent", "代理人；经纪人；作用剂", "n.", "Week 1 Day 3"),
  en("allergy", "过敏；过敏反应", "n.", "Week 1 Day 3"),
  en("alliance", "联盟；同盟", "n.", "Week 1 Day 3"),
  en("advertisement", "广告；公告", "n.", "Week 1 Day 3"),
  en("advance", "前进；提前；预付款", "v./n.", "Week 1 Day 3"),
  en("aggressive", "积极进取的；侵略性的", "adj.", "Week 1 Day 3"),
  en("aggressively", "积极地；强势地", "adv.", "Week 1 Day 3"),
  en("aid", "援助；帮助", "n./v.", "Week 1 Day 3"),
  en("allege", "声称；指控", "v.", "Week 1 Day 3"),
  en("allocation", "分配；配额", "n.", "已学习词汇"),
  en("allocate", "分配；划拨", "v.", "已学习词汇"),
  en("alter", "改变；修改", "v.", "已学习词汇"),
  en("amateur", "业余爱好者；业余的", "n./adj.", "已学习词汇"),
  en("ambulance", "救护车", "n.", "已学习词汇"),
  en("amount", "数量；总额", "n./v.", "已学习词汇"),
  en("anchor", "锚；主持人；使固定", "n./v.", "已学习词汇"),
  en("animated", "生动的；动画的", "adj.", "已学习词汇"),
  en("annoy", "使烦恼；打扰", "v.", "已学习词汇"),
  en("annoyed", "感到烦恼的", "adj.", "已学习词汇"),
  en("annoying", "令人烦恼的", "adj.", "已学习词汇"),
  en("antibiotic", "抗生素；抗菌的", "n./adj.", "已学习词汇"),
  en("antitrust", "反垄断的", "adj.", "已学习词汇"),
  en("apologetic", "道歉的；愧疚的", "adj.", "已学习词汇"),
  en("apology", "道歉；谢罪", "n.", "已学习词汇"),
  en("apologize", "道歉", "v.", "已学习词汇"),
  en("apparel", "服装；衣服", "n.", "已学习词汇"),
  en("application", "申请；应用；申请表", "n.", "已学习词汇"),
  en("appraise", "评估；评价", "v.", "已学习词汇"),
  en("apprehend", "逮捕；理解", "v.", "已学习词汇"),
  en("arraignment", "传讯；提审", "n.", "Week 1 Day 4"),
  en("arson", "纵火罪", "n.", "Week 1 Day 4"),
  en("arsonist", "纵火犯", "n.", "Week 1 Day 4"),
  en("artificial", "人造的；人工的", "adj.", "Week 1 Day 4"),
  en("assailant", "袭击者；攻击者", "n.", "Week 1 Day 4"),
  en("assassinate", "暗杀", "v.", "Week 1 Day 4"),
  en("assassin", "刺客；暗杀者", "n.", "Week 1 Day 4"),
  en("assemble", "集合；组装", "v.", "Week 1 Day 4"),
  en("assembled", "已集合的；已组装的", "adj.", "Week 1 Day 4"),
  en("assert", "断言；维护（权利）", "v.", "Week 1 Day 4"),
  en("asserted", "断言了；维护了", "v.", "Week 1 Day 4"),
  en("asset", "资产；有用的人或事物", "n.", "Week 1 Day 4"),
  en("assimilate", "吸收；同化；理解", "v.", "Week 1 Day 5"),
  en("asthma", "哮喘", "n.", "Week 1 Day 5"),
  en("astronomer", "天文学家", "n.", "Week 1 Day 5"),
  en("atomic", "原子的；原子能的", "adj.", "Week 1 Day 5"),
  en("attain", "达到；获得", "v.", "Week 1 Day 5"),
  en("attentive", "专心的；周到的", "adj.", "Week 1 Day 5"),
  en("attentively", "专心地；周到地", "adv.", "Week 1 Day 5"),

  ja("こんにちは", "こんにちは", "你好", "寒暄语", "基础词汇"),
  ja("ありがとう", "ありがとう", "谢谢", "寒暄语", "基础词汇"),
  ja("私", "わたし", "我", "代词", "基础词汇"),
  ja("日本", "にほん", "日本", "名词", "基础词汇"),
  ja("学生", "がくせい", "学生", "名词", "基础词汇"),
  ja("一", "いち", "一", "数词", "基础词汇"),
  ja("二", "に", "二", "数词", "基础词汇"),
  ja("三", "さん", "三", "数词", "基础词汇"),
  ja("朝", "あさ", "早晨", "名词", "每日时间"),
  ja("昼", "ひる", "白天；中午", "名词", "每日时间"),
  ja("夜", "よる", "夜晚", "名词", "每日时间"),
  ja("今日", "きょう", "今天", "名词", "每日时间"),
  ja("明日", "あした", "明天", "名词", "每日时间"),
  ja("食べます", "たべます", "吃", "动词", "基础动词"),
  ja("飲みます", "のみます", "喝", "动词", "基础动词"),
  ja("見ます", "みます", "看", "动词", "基础动词"),
  ja("行きます", "いきます", "去", "动词", "基础动词"),
  ja("寝ます", "ねます", "睡觉", "动词", "基础动词"),
  ja("学校", "がっこう", "学校", "名词", "场所词汇"),
  ja("家", "うち", "家", "名词", "场所词汇"),
  ja("店", "みせ", "商店", "名词", "场所词汇"),
  ja("図書館", "としょかん", "图书馆", "名词", "场所词汇"),
  ja("大きい", "おおきい", "大的", "形容词", "基础形容词"),
  ja("小さい", "ちいさい", "小的", "形容词", "基础形容词"),
  ja("暑い", "あつい", "天气热的", "形容词", "基础形容词"),
  ja("寒い", "さむい", "寒冷的", "形容词", "基础形容词"),
  ja("新しい", "あたらしい", "新的", "形容词", "基础形容词"),
  ja("部屋", "へや", "房间", "名词", "生活词汇"),
  ja("椅子", "いす", "椅子", "名词", "生活词汇"),
  ja("猫", "ねこ", "猫", "名词", "生活词汇"),
  ja("本", "ほん", "书", "名词", "生活词汇"),
  ja("電話", "でんわ", "电话", "名词", "生活词汇"),
  ja("かばん", "かばん", "包", "名词", "生活词汇"),
  ja("車", "くるま", "汽车", "名词", "生活词汇"),
  ja("水", "みず", "水", "名词", "饮食词汇"),
  ja("ご飯", "ごはん", "米饭；饭", "名词", "饮食词汇"),
  ja("魚", "さかな", "鱼", "名词", "饮食词汇"),
  ja("卵", "たまご", "鸡蛋", "名词", "饮食词汇"),
  ja("りんご", "りんご", "苹果", "名词", "饮食词汇"),
  ja("お茶", "おちゃ", "茶", "名词", "饮食词汇"),
  ja("晴れ", "はれ", "晴天", "名词", "天气词汇"),
  ja("雨", "あめ", "雨", "名词", "天气词汇"),
  ja("曇り", "くもり", "阴天", "名词", "天气词汇"),
  ja("雪", "ゆき", "雪", "名词", "天气词汇"),
  ja("天気", "てんき", "天气", "名词", "天气词汇"),
  ja("父", "ちち", "父亲（自己的）", "名词", "家庭词汇"),
  ja("母", "はは", "母亲（自己的）", "名词", "家庭词汇"),
  ja("兄", "あに", "哥哥（自己的）", "名词", "家庭词汇"),
  ja("姉", "あね", "姐姐（自己的）", "名词", "家庭词汇"),
  ja("家族", "かぞく", "家人；家庭", "名词", "家庭词汇"),

  ja("ここ", "ここ", "这里", "指示词", "第5课"),
  ja("あそこ", "あそこ", "那里", "指示词", "第5课"),
  ja("どこ", "どこ", "哪里", "疑问词", "第5课"),
  ja("そこ", "そこ", "那里", "指示词", "第5课"),
  ja("上", "うえ", "上面", "名词", "第5课"),
  ja("前", "まえ", "前面", "名词", "第5课"),
  { ...ja("近く", "ちかく", "附近", "名词", "第5课"), accent: 2, accentVerified: true },
  { ...ja("向こう", "むこう", "对面；那边", "名词", "第5课"), accent: 0, accentVerified: true },
  ja("隣", "となり", "旁边；隔壁", "名词", "第5课"),
  ja("そば", "そば", "旁边；附近", "名词", "第5课"),
  ja("何", "なに", "什么", "疑问词", "第5课"),
  ja("あります", "あります", "有；在（无生命）", "动词", "第5课"),
  ja("います", "います", "有；在（有生命）", "动词", "第5课"),
  ja("コップ", "コップ", "杯子", "名词", "第5课"),
  { ...ja("雑誌", "ざっし", "杂志", "名词", "第5课"), example: "机の上に雑誌があります。", translation: "桌子上有杂志。" },
  ja("犬", "いぬ", "狗", "名词", "第5课"),
  ja("ノート", "ノート", "笔记本", "名词", "第5课"),
  ja("男", "おとこ", "男人；男性", "名词", "第5课"),
  ja("男の人", "おとこのひと", "男人；男性", "名词", "第5课"),
  ja("教室", "きょうしつ", "教室", "名词", "第5课"),
  ja("トイレ", "トイレ", "洗手间", "名词", "第5课"),
  ja("机", "つくえ", "桌子", "名词", "第5课"),
  ja("食堂", "しょくどう", "食堂", "名词", "第5课"),
  ja("鉛筆", "えんぴつ", "铅笔", "名词", "第5课"),
  ja("会議室", "かいぎしつ", "会议室", "名词", "第5课"),
  { ...ja("入り口", "いりぐち", "入口", "名词", "第5课"), accent: 0, accentVerified: true },
  ja("ベンチ", "ベンチ", "长椅", "名词", "第5课"),
  ja("公園", "こうえん", "公园", "名词", "第5课"),
  ja("郵便局", "ゆうびんきょく", "邮局", "名词", "第5课"),
  ja("駅", "えき", "车站", "名词", "第5课"),
  ja("スーパー", "スーパー", "超市", "名词", "第5课"),
  ja("フィットネスジム", "フィットネスジム", "健身房", "名词", "第5课"),
  ja("コンビニ", "コンビニ", "便利店", "名词", "第5课"),
  ja("コインランドリー", "コインランドリー", "自助洗衣店", "名词", "第5课"),
  ja("引っ越し屋", "ひっこしや", "搬家公司", "名词", "第5课"),
  ja("タンス", "タンス", "衣柜；柜子", "名词", "第5课"),
  ja("棚", "たな", "架子；搁板", "名词", "第5课"),
  ja("箱", "はこ", "箱子", "名词", "第5课"),
  ja("自転車", "じてんしゃ", "自行车", "名词", "第5课"),
  ja("自転車屋", "じてんしゃや", "自行车店", "名词", "第5课"),
  ja("帽子", "ぼうし", "帽子", "名词", "第5课"),
  { ...ja("店員", "てんいん", "店员", "名词", "第5课"), accent: 2, accentVerified: true, example: "店員に聞きました。", translation: "我问了店员。" },
  ja("コーナー", "コーナー", "专区；角落", "名词", "第5课"),
  ja("服", "ふく", "衣服", "名词", "第5课"),
  { ...ja("売り場", "うりば", "柜台；售货处", "名词", "第5课"), example: "靴の売り場は二階です。", translation: "鞋类柜台在二楼。" },
  ja("先生", "せんせい", "老师", "名词", "第5课"),

  ja("一つ", "ひとつ", "一个", "数量词", "第6课", "current"),
  ja("三つ", "みっつ", "三个", "数量词", "第6课", "current"),
  ja("八つ", "やっつ", "八个", "数量词", "第6课", "current"),
  ja("しか", "しか", "只有；仅（与否定呼应）", "助词", "第6课", "current"),
  ja("クラス", "クラス", "班级", "名词", "第6课", "current"),
  ja("二人", "ふたり", "两个人", "数量词", "第6课", "current"),
  ja("五歳", "ごさい", "五岁", "数量词", "第6课", "current"),
  ja("枚", "まい", "张；枚（扁平物计数）", "助数词", "第6课", "current"),
  ja("台", "だい", "台（机器、车辆计数）", "助数词", "第6课", "current"),
  ja("三枚", "さんまい", "三张；三枚", "数量词", "第6课", "current"),
];
